default_install_hook_types: [pre-commit, pre-push]
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.15.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: "^(migrations/)"
      - id: trailing-whitespace
        exclude: "^(migrations/)"
      - id: no-commit-to-branch
        args: ["--branch", "main"]
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff
        name: Run ruff linter
        args: [--fix]
        stages: [pre-commit]
      - id: ruff-format
        name: Run ruff formatter
        stages: [pre-commit]
